### ISSUE TITLE
gitkraken does not support opening private repositories

### ISSUE THREAD

**Issue by zengletian1491** [5cr1pt/GitCracken#14]
This free version of Gitkraken does not support opening private repositories. I can not pull/push the project directly.
Thanks for suggestions!

**Comment by torriz** [comment]
@zengletian1491 Yes? You need to upgrade to GitKraken Individual/Pro to have access to private repos.
OR: use this patcher? :PPPPPPPPPPPPPPP

**Comment by zengletian1491** [comment]
Need to pay!(stupid enough!)

**Comment by zengletian1491** [comment]
Need to pay(stupidly enough).

**Comment by torriz** [comment]
using this patcher then u can open private repos as much as u want

**Comment by adrianjagielak** [comment]
@torriz having to create software and buy food from its revenue and then people steal that software for free without paying is stupid

**Comment by jampack** [comment]
> @torriz having to create software and buy food from its revenue and then people steal that software for free without paying is stupid

well starting as free and getting free marketing and then making it pay to use is also not fair

**Comment by 5cr1pt** [comment]
fixed.
