### ISSUE TITLE
yarn install Error - No longer working?

### ISSUE THREAD

**Issue by bauson-com** [5cr1pt/GitCracken#15]
`GitCracken/GitCracken on  master [?] is 📦 v0.6.1 via ⬢ v12.12.0
 yarn install
yarn install v1.19.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://backend.zhortech.com:4873/semver/-/semver-6.3.0.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jay/playground/GitCracken/GitCracken/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by bmbariah** [comment]
Delete both node_modules & yarn.lock then run yarn

**Comment by xyzlast** [comment]
using npm. instead of yarn.

**Comment by EugeneRymarev** [comment]
https://github.com/EugeneRymarev/GitCracken my fork with worked links for yarn
