### ISSUE TITLE
Update to 6.4.0 version

### ISSUE THREAD

**Issue by ka6an** [5cr1pt/GitCracken#16]

**Comment by AndreaMiotto** [comment]
it does not work with 6.4.0

**Comment by ka6an** [comment]
@5cr1pt could you please fix crack to 6.4.0 version?

**Comment by Dezeter** [comment]
> 
> 
> @5cr1pt could you please fix crack to 6.4.0 version?

This version sopported 6.4.0  https://i.imgur.com/HffFBJO.png

**Comment by ka6an** [comment]
@Dezeter How did you do this? Could we continue communication in vk or telegram?

**Comment by bohdantverdyi** [comment]
@ka6an  I reinstalled gitkraken on my laptop, after that pathcer works good.

**Comment by ka6an** [comment]
@bohdantverdyi yes, after reinstallation gitkraken pather worked!
Thank you!)
