### ISSUE TITLE
Error while patching

### ISSUE THREAD

**Issue by VladimirLarionov** [5cr1pt/GitCracken#17]
Hello !
When I am the patching get the error: 

Unexpected token: ... bla bla bla

Please fix this file --> appId.ts
In the line 36 it should probably be like this --> } catch (e) {
it's like this --> } catch  {

best regard

**Comment by adrianjagielak** [comment]
A little reminder, you can fix it yourself, firstly try the code with your fix and then make pull request to this repo. You can even do this without leaving the website, just open here specific file, click 'edit' to fork and then make a pull request

**Comment by adrianjagielak** [comment]
this is called open source

**Comment by VladimirLarionov** [comment]
I don't know how to use the Git yet. I'm afraid to break the program. I study the Git, I will fix it as soon as I understand how to do it correctly.

**Comment by VladimirLarionov** [comment]
I did a pull request  appId.ts.
