### ISSUE TITLE
Unclear patching instructions

### ISSUE THREAD

**Issue by SMB41** [5cr1pt/GitCracken#23]
I've tried reading both README files, but I'm still quite confused as to what I'm supposed to do and where in order to apply this patch.

It lists lots of commands that I'm supposed to enter... where, exactly?

**Comment by ijat** [comment]
If you're using linux:

```
git clone https://github.com/5cr1pt/GitCracken.git
cd GitCracken/GitCracken
rm yarn.lock
yarn install
yarn build
wget https://release.gitkraken.com/linux/gitkraken-amd64.tar.gz
tar -xvzf gitkraken-amd64.tar.gz
node dist/bin/gitcracken.js patcher --asar gitkraken/resources/app.asar
gitkraken/gitkraken
```
It should show **PRO** version at the bottom of the app.

**Comment by elainegasca** [comment]
> If you're using linux:
> 
> ```
> git clone https://github.com/5cr1pt/GitCracken.git
> cd GitCracken/GitCracken
> rm yarn.lock
> yarn install
> yarn build
> wget https://release.gitkraken.com/linux/gitkraken-amd64.tar.gz
> tar -xvzf gitkraken-amd64.tar.gz
> node dist/bin/gitcracken.js patcher --asar gitkraken/resources/app.asar
> gitkraken/gitkraken
> ```
> 
> It should show **PRO** version at the bottom of the app.

That works nice, thanks.

**Comment by MortimerMarsyja** [comment]
how do I use it with mac?

**Comment by 5cr1pt** [comment]
> how do I use it with mac?

quick start works on macOS .
