### ISSUE TITLE
not working on 6.5.2 on mac

### ISSUE THREAD

**Issue by smmousavi76** [5cr1pt/GitCracken#26]
It's not working on  new version 6.5.2

**Comment by JourneyOver** [comment]
It's the same on windows as well, so your first title was correct. It's currently just not working at allon 6.5.2 which is sad as I can no longer open my private repositories now :(

**Comment by ClementRb** [comment]
> It's the same on windows as well, so your first title was correct. It's currently just not working at all on 6.5.2 which is sad as I can no longer open my private repositories now :(
> 
> Edit: I've just decided to revert back to 6.5.1 for the time being until someone can come along with a fix. It's pretty easy to revert back as gitkraken keeps the older version around as well and it's still in it's "pro" state while 6.5.2 is in a "free" state.

How do you revert back to 6.5.1 ?

**Comment by alexey-gorshkov** [comment]
> > It's the same on windows as well, so your first title was correct. It's currently just not working at all on 6.5.2 which is sad as I can no longer open my private repositories now :(
> > Edit: I've just decided to revert back to 6.5.1 for the time being until someone can come along with a fix. It's pretty easy to revert back as gitkraken keeps the older version around as well and it's still in it's "pro" state while 6.5.2 is in a "free" state.
> 
> How do you revert back to 6.5.1 ?

https://release.gitkraken.com/darwin/GitKraken-v6.5.1.zip

**Comment by JourneyOver** [comment]
> > It's the same on windows as well, so your first title was correct. It's currently just not working at all on 6.5.2 which is sad as I can no longer open my private repositories now :(
> > Edit: I've just decided to revert back to 6.5.1 for the time being until someone can come along with a fix. It's pretty easy to revert back as gitkraken keeps the older version around as well and it's still in it's "pro" state while 6.5.2 is in a "free" state.
> 
> How do you revert back to 6.5.1 ?

Just go to wherever gitkraken is installed (for me it is in %LOCALAPPDATA%/gitkraken) and you should see a folder for the latest version and a folder for an older version just go into the older version folder and use the gitkraken.exe from that, any shortcuts that you or gitkraken has made will need to have the target field switched to said older version as well.

Don't seem to need to worry about it updating itself either from the older version to the newer one, as I have not seen hide nor hair of it requesting to update after switching back to an older release (even though it still does seem to check for updates).

**Comment by AlonsoK28** [comment]
I've only
`app-6.5.2
app-6.5.3`

What can I do?


> > > It's the same on windows as well, so your first title was correct. It's currently just not working at all on 6.5.2 which is sad as I can no longer open my private repositories now :(
> > > Edit: I've just decided to revert back to 6.5.1 for the time being until someone can come along with a fix. It's pretty easy to revert back as gitkraken keeps the older version around as well and it's still in it's "pro" state while 6.5.2 is in a "free" state.
> > 
> > 
> > How do you revert back to 6.5.1 ?
> 
> Just go to wherever gitkraken is installed (for me it is in %LOCALAPPDATA%/gitkraken) and you should see a folder for the latest version and a folder for an older version just go into the older version folder and use the gitkraken.exe from that, any shortcuts that you or gitkraken has made will need to have the target field switched to said older version as well.

**Comment by JourneyOver** [comment]
Couldn't say @AlonsoK28 

it seems that with the release of 6.5.3, it's not even possible to open 6.5.1 anymore, as upon closing it and re-opening it just sits at "opening kitkraken" indefinitely.

**Comment by ftuyama** [comment]
You can install an older version using https://iusethis.luo.ma/gitkraken/

**Comment by modernpk** [comment]
@ftuyama can you also provide .exe version?

**Comment by ClementRb** [comment]
> @ftuyama can you also provide .exe version?

https://release.gitkraken.com/win64/GitKrakenSetup-6.5.1.exe

**Comment by ftuyama** [comment]
I can't prevent it from updating to 6.5.3 on macOS. Can't access previous versions, either. Maybe there's some way to edit /etc/hosts on macOS to prevent the update?

**Comment by quyen194** [comment]
add to hosts
127.0.0.1 release.gitkraken.com

**Comment by JourneyOver** [comment]
Ways to prevent updates:

Remove the update.exe located in `%localappdata%/gitkraken` (for windows)

or

Add `127.0.0.1 release.gitkraken.com` to your host file located in `C:\Windows\System32\drivers\etc` (for windows)

Same can be done for other OS's just need to find where those items are located

**Comment by gkshi** [comment]
I think it will be useful.

Download v6.5.1 here (macos dmg)
https://yadi.sk/d/8HLxSirthO2HFA

sudo nano /etc/hosts
127.0.0.1 release.axocdn.com
(It blocks gitkraken auto update)

Patch gitkraken as usual (after first open)

I've tested and it works fine.

**Comment by reach4bawer** [comment]
@gkshi I tried to follow the instructions but it does not seem to work for me. I work behind a proxy on a macbook. Despite adding the entry in the /etc/hosts my GitKraken keeps updating. At first I thought that it was my hosts file, so I made a new one but no luck.
The following is my hosts file -
```
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost

127.0.0.1 release.axocdn.com
127.0.0.1 release.gitkraken.com
```

But on starting GitKraken the application would still update itself. 
Am I doing something wrong? 
Is there a different way to block the connection or update process ?

**Comment by AlonsoK28** [comment]
Is it working again?

**Comment by 5cr1pt** [comment]
Yes, update works well.

**Comment by AlonsoK28** [comment]
> @gkshi I tried to follow the instructions but it does not seem to work for me. I work behind a proxy on a macbook. Despite adding the entry in the /etc/hosts my GitKraken keeps updating. At first I thought that it was my hosts file, so I made a new one but no luck.
> The following is my hosts file -
> 
> ```
> 127.0.0.1 localhost
> 255.255.255.255 broadcasthost
> ::1 localhost
> fe80::1%lo0 localhost
> 
> 127.0.0.1 release.axocdn.com
> 127.0.0.1 release.gitkraken.com
> ```
> 
> But on starting GitKraken the application would still update itself.
> Am I doing something wrong?
> Is there a different way to block the connection or update process ?

Uninstall your Gitkraken from MACOS using this app `CleanMyMac X` https://apps.apple.com/mx/app/cleanmymac-x/id1339170533?mt=12 and then try `path` again

**Comment by AlonsoK28** [comment]
> Yes, update works well.

New `7.2.0` update disable `PRO EDITION` for me on `MAC OS`, I have tried several times using patch to go back to `PRO EDITION`
