### ISSUE TITLE
Error v6.5.3 Linux

### ISSUE THREAD

**Issue by cleitonsb** [5cr1pt/GitCracken#29]
(node:8994) UnhandledPromiseRejectionWarning: Error: Can't patch static/index.js

Someone now how I can fix this?

**Comment by luyang93** [comment]
you should discribe your command detailedly

**Comment by jampack** [comment]
so it really is not patching the new version

**Comment by luyang93** [comment]
Gitkraken released new version 6.5.4.
You may cover /usr/share/gitkraken/resources by using the following file.
https://send.firefox.com/download/73a8e86da8e36c43/#tqOekUQlVkCt2ylCo7-WbQ
I'm not sure it will work on different linux distributions

**Comment by jampack** [comment]
@luyang93 on what distro u tried and it worked?

**Comment by luyang93** [comment]
you don't need to change to my distribution.if it doesn't work well,you need to build it self

**Comment by jampack** [comment]
> Gitkraken released new version 6.5.4.
> You may replace /usr/share/gitkraken/resources by using the following file.
> https://send.firefox.com/download/73a8e86da8e36c43/#tqOekUQlVkCt2ylCo7-WbQ
> I'm not sure it will work on different linux distributions

it worked on ubuntu 18, thanks alot

**Comment by PashaGeronimo** [comment]
> https://send.firefox.com/download/73a8e86da8e36c43/#tqOekUQlVkCt2ylCo7-WbQ
the link is no longer valid.
can you upload again?

**Comment by jampack** [comment]
@PashaGeronimo https://www.transfernow.net/ddl/gitkraken the link will remain valid for 72 hours from now. just uploaded so it might take a few minutes until they verify the upload

**Comment by AkgunFatih** [comment]
> @PashaGeronimo https://www.transfernow.net/ddl/gitkraken `the link expires in 6 days at 11h25 (GMT)`. Just uploaded it so it might take a few minutes until they verify the upload.

this mota foka realy works x

**Comment by Drjacky** [comment]
> resources

How about macOs?
The patcher says Successfully Done! But still, I see the trial 6 days. And about this path: `/usr/share/gitkraken/resources` we don't have it in macOS.
I do not find any `app.asar` at all in the whole storage!

**Comment by Drjacky** [comment]
> Gitkraken released new version 6.5.4.
> You may replace /usr/share/gitkraken/resources by using the following file.
> https://send.firefox.com/download/73a8e86da8e36c43/#tqOekUQlVkCt2ylCo7-WbQ
> I'm not sure it will work on different linux distributions

@jampack @luyang93 I'm using macOS, I copied those 2 files and a folder from extracted resources.tar.gz to `/Applications/GitKraken.app/Contents/Resources/HERE`, but still, when I run the software, it shows the trial label on the bottom!

**Comment by jampack** [comment]
@Drjacky @luyang93 might help you with this how to build it your self because we face errors when we try to build it for newer versions

**Comment by miguelmartinezinf** [comment]
@jampack could you upload it again please? facing same error...
thx in advance!

**Comment by jampack** [comment]
@miguelmartinezinf i think this has been fixed in the latest version but here is the link: https://www.transfernow.net/ddl/GitKraken-Resources

**Comment by jampack** [comment]
> > Gitkraken released new version 6.5.4.
> > You may replace /usr/share/gitkraken/resources by using the following file.
> > https://send.firefox.com/download/73a8e86da8e36c43/#tqOekUQlVkCt2ylCo7-WbQ
> > I'm not sure it will work on different linux distributions
> 
> @jampack @luyang93 I'm using macOS, I copied those 2 files and a folder from extracted resources.tar.gz to `/Applications/GitKraken.app/Contents/Resources/HERE`, but still, when I run the software, it shows the trial label on the bottom!

download and install the zip version don't download through package managers

**Comment by miguelmartinezinf** [comment]
@jampack thx a lot but It didnt work... do you know any other way? :D

**Comment by AchmadFathoni** [comment]
> Can't patch static/index.js

Try reinstall your gitkraken then patch it again

**Comment by AchmadFathoni** [comment]
> (node:8994) UnhandledPromiseRejectionWarning: Error: Can't patch static/index.js
> 
> Someone now how I can fix this?
Try reinstall your gitkraken then patch it again
