### ISSUE TITLE
Portable Gitkraken Windows 10

### ISSUE THREAD

**Issue by AlonsoK28** [5cr1pt/GitCracken#32]
Anybody knows if its possible use Gitkraken in a Portable ZIP version on Windows 10?

For example here is the Portable ZIP version of Visual Studio Code https://code.visualstudio.com/docs/editor/portable

Exist something similar for Gitkraken?

**Comment by TheWolfinator** [comment]
You can use thinapp to create portable app

**Comment by AlonsoK28** [comment]
Thanks a lot 

I'm going to try. 

😁

**Comment by kzk888** [comment]
> Thanks a lot
> 
> I'm going to try.
> 
> 😁

Is your try successfully?
