### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Rantoniaina** [5cr1pt/GitCracken#35]
After auto update, npm run gitcracken patcher doesn't have effect on the new version of GitKraken anymore.

**Comment by djmemo** [comment]
For me it's no problem (version 6.6.0), you did the following orders right? 
```
git clone https://github.com/5cr1pt/GitCracken.git
cd GitCracken/GitCracken/
yarn install
yarn build
node dist/bin/gitcracken.js patcher
```

**Comment by Rantoniaina** [comment]
I have cloned it about 4 months ago, but I follow the same order as you, should I reclone it?

**Comment by djmemo** [comment]
The last commit was March 24th. He forged a git pull.

**Comment by Rantoniaina** [comment]
All things work, thanks for your help.
