### ISSUE TITLE
Support for 7.0.0

### ISSUE THREAD

**Issue by creazy231** [5cr1pt/GitCracken#37]
Has someone tried this tool with the newest Version 7.0.0?

**Comment by djmemo** [comment]
I'm on Windows 10/GitKraken 7.0.0
The patch works for version 6.5+ and 7.0.0

**Comment by nolddor** [comment]
Worked OK on Debian Bullseye as well.

**Comment by djmemo** [comment]
It also supports version 7.0.1 #42

**Comment by hcc-israel** [comment]
works on 7.0.1

**Comment by AnonBit** [comment]
works on 7.1.0

**Comment by simon-mao** [comment]
works on 7.1.0

**Comment by rever96** [comment]
does it works on 7.3.2?

**Comment by AnonBit** [comment]
works on 7.2.0
PS. latest now is 7.2.0
