### ISSUE TITLE
How to know if the patch worked?

### ISSUE THREAD

**Issue by Drjacky** [5cr1pt/GitCracken#46]
When I click on the PRO icon on the bottom bar, I see this:
<img width="1232" alt="Screen Shot 2020-07-21 at 11 15 26" src="https://user-images.githubusercontent.com/2296754/88036172-7b4b4800-cb43-11ea-842b-6b8f4f77cba1.png">

GitKraken Version: 7.1.0

**Comment by djmemo** [comment]
We have to see if there has been a major change in the code.

**Comment by Drjacky** [comment]
@djmemo But how we(as a user) can check? Any specific icon or label might be removed?

**Comment by djmemo** [comment]
I just checked it's normal behavior, you had all the features of the PRO version.
