### ISSUE TITLE
Doesn't work for standalone

### ISSUE THREAD

**Issue by larrysolis** [5cr1pt/GitCracken#6]
Standalone asks for license

**Comment by lurumdare** [comment]
Version?

**Comment by larrysolis** [comment]
6.1.4. Standalone /offline version...

**Comment by lurumdare** [comment]
https://i.imgur.com/sEAn1pB.png work with internet

**Comment by larrysolis** [comment]
Yeah works for the online version.. The standalone is the offline version...
