### ISSUE TITLE
GitKraken 7.4.1 (for Mac OS) needs new patch ?

### ISSUE THREAD

**Issue by QuynhNhuNGUYEN** [5cr1pt/GitCracken#63]
<img width="725" alt="Capture d’écran 2020-12-03 à 10 12 56" src="https://user-images.githubusercontent.com/32763520/100991289-225cd900-3553-11eb-884b-13baa02c1ef8.png">

**Comment by vrnvorona** [comment]
@QuynhNhuNGUYEN you need to repeat process, but it will work. Any update needs patching.

**Comment by QuynhNhuNGUYEN** [comment]
Thanks @vrnvorona !
