### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory \AppData\Local\gitkraken\app-7.3.2\resources\ app\src\render\static\entryPoints\main\index.js

### ISSUE THREAD

**Issue by oliviervanbulck** [5cr1pt/GitCracken#66]
I get this error:

` UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or di
rectory, open 'C:\Users\werkprofiel\AppData\Local\gitkraken\app-7.3.2\resources\
app\src\render\static\entryPoints\main\index.js'
`

Then the crack fails and it changed nothing.

**Comment by oliviervanbulck** [comment]
Problem was installer for older version.

**Comment by peterKostovcikCapco** [comment]
@oliviervanbulck  what do you mean by "installer for older version"? I'm having the same issue now installing for 7.5.2

**Comment by oliviervanbulck** [comment]
> @oliviervanbulck what do you mean by "installer for older version"? I'm having the same issue now installing for 7.5.2

I had an old installer for gitkraken and installed it from there first. But obviously it doesn't work on older versions of Gitkraken anymore.
