### ISSUE TITLE
Opent Glo not working

### ISSUE THREAD

**Issue by tula-Intelads** [5cr1pt/GitCracken#8]
How to using Open Glo affter crack

**Comment by torriz** [comment]
+1 Glo/Glo Boards seem to be broken after patching... Any ideas?

**Comment by AlonsoK28** [comment]
> +1 Glo/Glo Boards seem to be broken after patching... Any ideas on unlocking Pro functionality and also use Free Glo?

If you are using `VSCode IDE` install `GitKraken Glo extension`

https://marketplace.visualstudio.com/items?itemName=axosoft.gitkraken-glo
